title: Social Computing Conference Deadlines
description: Countdowns to top Social Computing conference deadlines
author: Social Computing Lab. at NAIST, Japan

domain: "sociocom.github.io"
url: "https://sociocom.github.io"
baseurl: "/sociocom-deadlines"

twitter_hashtag: machinelearning
github_username: sociocom
github_repo: sociocom-deadlines

markdown: kramdown
ga_id:

include: ["_pages"]
